// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg4k4o2oywf6vzfclgMovwHEuEn6_pKYo',
    appId: '1:34230226310:web:ee349d1b5af3d0c7707007',
    messagingSenderId: '34230226310',
    projectId: 'medical-app-9cfaf',
    authDomain: 'medical-app-9cfaf.firebaseapp.com',
    databaseURL: 'https://medical-app-9cfaf-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'medical-app-9cfaf.appspot.com',
    measurementId: 'G-0VQ3H36TCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsKZ4zX_o2R-1gCC7ZWgKNg80Ub_XaE9k',
    appId: '1:34230226310:android:1331825e29a9e3f6707007',
    messagingSenderId: '34230226310',
    projectId: 'medical-app-9cfaf',
    databaseURL: 'https://medical-app-9cfaf-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'medical-app-9cfaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1obwazUGnZJmQq_Nbh3nkHoEV4GdvncE',
    appId: '1:34230226310:ios:bbad4caeaa87bcad707007',
    messagingSenderId: '34230226310',
    projectId: 'medical-app-9cfaf',
    databaseURL: 'https://medical-app-9cfaf-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'medical-app-9cfaf.appspot.com',
    iosBundleId: 'com.medapp.medicalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg4k4o2oywf6vzfclgMovwHEuEn6_pKYo',
    appId: '1:34230226310:web:f37c9a0b7bdf30af707007',
    messagingSenderId: '34230226310',
    projectId: 'medical-app-9cfaf',
    authDomain: 'medical-app-9cfaf.firebaseapp.com',
    databaseURL: 'https://medical-app-9cfaf-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'medical-app-9cfaf.appspot.com',
    measurementId: 'G-DXELM3G4XS',
  );

}